version: '2'
services:
  mysql:
    image: mysql:5.5.42
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - mysql
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_HOST=mysql:3306
  jwks-provider:
    image: graphql/jwks-provider
    environment:
      - PORT=80
  oauth:
    image: graphql/oauth
    links:
      - mysql
      - jwks-provider
    ports:
      - 8002:80
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/test?parseTime=true
      - JWKS_PROVIDER_URL=http://jwks-provider/private/jwks.json
  app:
    build: .
    restart: always
    ports:
      - 8000:80
    links:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/test?parseTime=true
  test:
    image: jakubknejzlik/godog-graphql
    links:
      - app
    volumes:
      - ./features:/godog/features
    environment:
      - GRAPHQL_URL=http://app/graphql
