// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package memberships

type MembershipInput struct {
	MemberID string  `json:"memberID"`
	EntityID string  `json:"entityID"`
	Entity   *string `json:"entity"`
	Role     *string `json:"role"`
}

type MembershipInvitationInput struct {
	Email    string  `json:"email"`
	EntityID string  `json:"entityID"`
	Entity   *string `json:"entity"`
	Role     *string `json:"role"`
}

type _Service struct {
	Sdl *string `json:"sdl"`
}
